{
 "title": "Aerospike Tinker Bench",
 "description": "Aerospike Tinker Bench Query Runner",
 "tags": [
  "TinkerBench",
  "Aerospike",
  "Graph",
  "AGS"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DATASOURCE", "label": "Data Source", "query": "prometheus" },
   {
    "name": "client",
    "label": "Workload Clients",
    "query": {
     "query": "label_values(aerospike_workload_ags_stateinfo,instance)"
    }
   },
   {
    "name": "pid",
    "label": "PID",
    "query": {
     "query": "label_values(aerospike_workload_ags_stateinfo{instance=~\"$client\"},pid)"
    }
   },
   {
    "name": "workload",
    "label": "Workload",
    "query": {
     "query": "label_values(aerospike_workload_ags_stateinfo{instance=~\"$client\", pid=~\"$pid\"},workload)"
    }
   },
   {
    "name": "workloadstage",
    "label": "Workload Stage",
    "query": {
     "query": "label_values(aerospike_workload_ags_stateinfo{instance=~\"$client\", workload=~\"$workload\", pid=~\"$pid\"},wlstage)"
    }
   },
   {
    "name": "workloadtype",
    "label": "Workload Type",
    "query": {
     "query": "label_values(aerospike_workload_ags_stateinfo{instance=~\"$client\", workload=~\"$workload\", pid=~\"$pid\"},wltype)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Workload",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "aerospike_workload_ags_stateinfo{instance=~\"$client\", pid=~\"$pid\", workload=~\"$workload\", wltype=~\"$workloadtype\", type=\"static\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Start and Completion Time",
   "type": "stat",
   "description": "The workload's starting and completion time",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_workload_ags_stateinfo{instance=~\"$client\", pid=~\"$pid\", type=\"static\", workload=~\"$workload\", wltype=~\"$workloadtype\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Configuration Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CLI Arguments",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "aerospike_workload_ags_stateinfo{instance=~\"$client\", pid=~\"$pid\", workload=~\"$workload\", type=\"static\", wltype=~\"$workloadtype\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workload Type",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_workload_ags_stateinfo{instance=~\"$client\", pid=~\"$pid\", workload=~\"$workload\", wltype=~\"$workloadtype\", type=\"static\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Targeted Queries per Second",
   "type": "stat",
   "description": "The targeted Queries per second provided by the CLI",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_workload_ags_stateinfo{instance=~\"$client\", pid=~\"$pid\", workload=~\"$workload\", type=\"static\", wltype=~\"$workloadtype\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS Increment",
   "type": "stat",
   "description": "The rate incremented from last QPS",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_workload_ags_stateinfo{instance=~\"$client\", pid=~\"$pid\", workload=~\"$workload\", type=\"static\", wltype=~\"$workloadtype\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ending QPS",
   "type": "stat",
   "description": "Stop running when this QPS is reached.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_workload_ags_stateinfo{instance=~\"$client\", pid=~\"$pid\", workload=~\"$workload\", type=\"static\", wltype=~\"$workloadtype\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS Percent",
   "type": "stat",
   "description": "The percent of the QPS rate that will be considered Good",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_workload_ags_stateinfo{instance=~\"$client\", pid=~\"$pid\", workload=~\"$workload\", type=\"static\", wltype=~\"$workloadtype\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Targeted Schedulers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_workload_ags_stateinfo{instance=~\"$client\", pid=~\"$pid\", workload=~\"$workload\", type=\"static\", wltype=~\"$workloadtype\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Targeted Workers",
   "type": "stat",
   "description": "The number of workers per scheduler",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_workload_ags_stateinfo{instance=~\"$client\", pid=~\"$pid\", workload=~\"$workload\", type=\"static\", wltype=~\"$workloadtype\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_workload_ags_stateinfo{instance=~\"$client\", pid=~\"$pid\", workload=~\"$workload\", type=\"static\", wltype=~\"$workloadtype\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Targeted Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_workload_ags_stateinfo{instance=~\"$client\", pid=~\"$pid\", workload=~\"$workload\", type=\"static\", wltype=~\"$workloadtype\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ids/Values Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Manager Type",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "aerospike_workload_ags_idmgrinfo{instance=~\"$client\", pid=~\"$pid\", workload=~\"$workload\", wltype=~\"$workloadtype\", type=\"static\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Gremlin Id Query",
     "type": "table",
     "description": "Used this query to obtain Ids",
     "gridPos": { "h": 8, "w": 10, "x": 5, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "expr": "aerospike_workload_ags_idmgrinfo{instance=~\"$client\", pid=~\"$pid\", workload=~\"$workload\", wltype=~\"$workloadtype\", type=\"static\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Parent Nodes",
     "type": "stat",
     "description": "Top Level Nodes",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "aerospike_workload_ags_idmgrinfo{instance=~\"$client\", pid=~\"$pid\", workload=~\"$workload\", wltype=~\"$workloadtype\", type=\"static\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Depth",
     "type": "stat",
     "description": "The depth required to satisfy the Query",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "aerospike_workload_ags_idmgrinfo{instance=~\"$client\", pid=~\"$pid\", workload=~\"$workload\", wltype=~\"$workloadtype\", type=\"static\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Possible Relationships",
     "type": "stat",
     "description": "The maximum possible relationships",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "aerospike_workload_ags_idmgrinfo{instance=~\"$client\", pid=~\"$pid\",workload=~\"$workload\", wltype=~\"$workloadtype\", type=\"static\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Distinct Ids",
     "type": "stat",
     "description": "The number of distinct ids",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "aerospike_workload_ags_idmgrinfo{instance=~\"$client\", pid=~\"$pid\",workload=~\"$workload\", wltype=~\"$workloadtype\", type=\"static\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Possible Depth",
     "type": "stat",
     "description": "The maximum possible depth",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "aerospike_workload_ags_idmgrinfo{instance=~\"$client\", pid=~\"$pid\",workload=~\"$workload\", wltype=~\"$workloadtype\", type=\"static\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Running Time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "aerospike_workload_ags_idmgrinfo{instance=~\"$client\", pid=~\"$pid\",workload=~\"$workload\", wltype=~\"$workloadtype\", type=\"static\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Warmup Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "aerospike_workload_ags_stateinfo{instance=~\"$client\", pid=~\"$pid\",workload=~\"$workload\", type=\"static\", wlstage=\"Warmup\", wltype=~\"$workloadtype\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Completed Calls",
     "type": "stat",
     "description": "The total completed number of write actions across all types",
     "gridPos": { "h": 5, "w": 4, "x": 3, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(last_over_time(aerospike_workload_ags_lng_latency_milliseconds_count{instance=~\"$client\", pid=~\"$pid\", workload=~\"$workload\", wltype=~\"$workloadtype\", wlstage=\"Warmup\"}[$__interval]))",
       "legendFormat": "Not Measured"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "stat",
     "description": "The total number oferrors",
     "gridPos": { "h": 5, "w": 3, "x": 7, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(last_over_time(aerospike_workload_ags_exception_total{instance=~\"$client\", pid=~\"$pid\",workload=~\"$workload\", wltype=~\"$workloadtype\", wlstage=\"Warmup\"}[$__interval]))",
       "legendFormat": "Not Measured"
      },
      {
       "expr": "aerospike_workload_ags_stateinfo{instance=~\"$client\", pid=~\"$pid\",wltype=~\"$workloadtype\", workload=~\"$workload\", type=\"static\", wlstage=\"Warmup\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Running Time",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 10, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "diff" ] } },
     "targets": [
      {
       "expr": "timestamp(aerospike_workload_ags_stateinfo{instance=~\"$client\", pid=~\"$pid\",workload=~\"$workload\", wltype=~\"$workloadtype\", wlstage=\"Warmup\"})",
       "legendFormat": "{{wlstage}} {{DBConnState}}"
      },
      {
       "expr": "sort(aerospike_workload_ags_stateinfo{instance=~\"$client\", pid=~\"$pid\",workload=~\"$workload\", wltype=~\"$workloadtype\", wlstage=\"Warmup\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Running QPS",
     "type": "stat",
     "description": "Current QPS Rate",
     "gridPos": { "h": 5, "w": 7, "x": 14, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "aerospike_workload_ags_currentQPS{instance=~\"$client\", pid=~\"$pid\",workload=~\"$workload\", wltype=~\"$workloadtype\", wlstage=\"Warmup\"} > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency Percentiles (Estimated)",
     "type": "stat",
     "description": "Estimated latency based on scraping rate. It is suggested to obtain accurate latency percentiles to view the console/log reports.",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg by (wltype) (histogram_quantile(0.50, (aerospike_workload_ags_lng_latency_milliseconds_bucket{instance=~\"$client\", pid=~\"$pid\",workload=~\"$workload\", wltype=~\"$workloadtype\", wlstage=\"Warmup\"})))",
       "legendFormat": "p50"
      },
      {
       "expr": "avg by (wltype) (histogram_quantile(0.95, (aerospike_workload_ags_lng_latency_milliseconds_bucket{instance=~\"$client\", pid=~\"$pid\", workload=~\"$workload\", wltype=~\"$workloadtype\", wlstage=\"Warmup\"})))",
       "legendFormat": "p95"
      },
      {
       "expr": "avg by (wltype) (histogram_quantile(0.99, (aerospike_workload_ags_lng_latency_milliseconds_bucket{instance=~\"$client\", pid=~\"$pid\",workload=~\"$workload\", wltype=~\"$workloadtype\", wlstage=\"Warmup\"})))",
       "legendFormat": "p99"
      },
      {
       "expr": "avg by (wltype) (histogram_quantile(0.999, (aerospike_workload_ags_lng_latency_milliseconds_bucket{instance=~\"$client\", pid=~\"$pid\", workload=~\"$workload\", wltype=~\"$workloadtype\", wlstage=\"Warmup\"})))",
       "legendFormat": "p99.9"
      }
     ]
    }
   ]
  },
  { "title": "Workload Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_workload_ags_stateinfo{instance=~\"$client\", pid=~\"$pid\", workload=~\"$workload\", wltype=~\"$workloadtype\", type=\"static\", wlstage=\"Workload\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Completed Calls",
   "type": "stat",
   "description": "The total completed number of write actions across all types",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(last_over_time(aerospike_workload_ags_lng_latency_milliseconds_count{instance=~\"$client\", pid=~\"$pid\", workload=~\"$workload\", wltype=~\"$workloadtype\", wlstage=\"Workload\"}[$__interval]))",
     "legendFormat": "Not Measured"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "The total number oferrors",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(aerospike_workload_ags_exception_total{instance=~\"$client\", pid=~\"$pid\", workload=~\"$workload\", wltype=~\"$workloadtype\", wlstage=\"Workload\"}[$__interval]))",
     "legendFormat": "Not Measured"
    },
    {
     "expr": "aerospike_workload_ags_stateinfo{instance=~\"$client\", pid=~\"$pid\", wltype=~\"$workloadtype\", workload=~\"$workload\", type=\"static\", wlstage=\"Workload\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "timestamp(aerospike_workload_ags_stateinfo{instance=~\"$client\", pid=~\"$pid\", workload=~\"$workload\", wltype=~\"$workloadtype\", wlstage=\"Workload\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sort(aerospike_workload_ags_stateinfo{instance=~\"$client\", pid=~\"$pid\", workload=~\"$workload\", wltype=~\"$workloadtype\", wlstage=\"Workload\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running QPS",
   "type": "stat",
   "description": "Current QPS Rate",
   "gridPos": { "h": 5, "w": 7, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_workload_ags_currentQPS{instance=~\"$client\", pid=~\"$pid\", workload=~\"$workload\", wltype=~\"$workloadtype\", wlstage=\"Workload\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Percentiles (Estimated)",
   "type": "stat",
   "description": "Estimated latency based on scraping rate. It is suggested to obtain accurate latency percentiles to view the console/log reports.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (wltype) (histogram_quantile(0.50, (aerospike_workload_ags_lng_latency_milliseconds_bucket{instance=~\"$client\", pid=~\"$pid\", workload=~\"$workload\", wltype=~\"$workloadtype\", wlstage=\"Workload\"})))",
     "legendFormat": "p50"
    },
    {
     "expr": "avg by (wltype) (histogram_quantile(0.95, (aerospike_workload_ags_lng_latency_milliseconds_bucket{instance=~\"$client\", pid=~\"$pid\", workload=~\"$workload\", wltype=~\"$workloadtype\", wlstage=\"Workload\"})))",
     "legendFormat": "p95"
    },
    {
     "expr": "avg by (wltype) (histogram_quantile(0.99, (aerospike_workload_ags_lng_latency_milliseconds_bucket{instance=~\"$client\", workload=~\"$workload\", wltype=~\"$workloadtype\", wlstage=\"Workload\"})))",
     "legendFormat": "p99"
    },
    {
     "expr": "avg by (wltype) (histogram_quantile(0.999, (aerospike_workload_ags_lng_latency_milliseconds_bucket{instance=~\"$client\", pid=~\"$pid\", workload=~\"$workload\", wltype=~\"$workloadtype\", wlstage=\"Workload\"})))",
     "legendFormat": "p99.9"
    }
   ]
  },
  { "title": "Runtime Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Queries per Second",
   "type": "timeseries",
   "description": "The number of queries per second.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "aerospike_workload_ags_currentQPS{instance=~\"$client\", pid=~\"$pid\", workload=~\"$workload\", wltype=~\"$workloadtype\", wlstage=~\"$workloadstage\"} > 0",
     "legendFormat": "{{wlstage}}-{{wltype}} {{pid}}"
    }
   ]
  },
  {
   "title": "Client Queue Depth",
   "type": "timeseries",
   "description": "Pending Query Execution Queue. This is an indictor of how well Tinker Bench 2 is handling the target QPS.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "aerospike_workload_ags_pending_run_queue{instance=~\"$client\", pid=~\"$pid\", workload=~\"$workload\", wltype=~\"$workloadtype\", wlstage=~\"$workloadstage\"}",
     "legendFormat": "{{wlstage}}-{{wltype}} {{pid}}"
    }
   ]
  },
  {
   "title": "Error Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Error",
     "type": "table",
     "description": "All Errors",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "aerospike_workload_ags_exception_total{instance=~\"$client\", pid=~\"$pid\", workload=~\"$workload\", wltype=~\"$workloadtype\", wlstage=~\"$workloadstage\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "All Error",
     "type": "timeseries",
     "description": "All Errors",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "aerospike_workload_ags_exception_total{instance=~\"$client\", pid=~\"$pid\", workload=~\"$workload\", wltype=~\"$workloadtype\", wlstage=~\"$workloadstage\"}",
       "legendFormat": "{{wlstage}}-{{wltype}} {{pid}} - {{exception_type}}: {{exception}}"
      }
     ]
    }
   ]
  }
 ]
}